### ISSUE TITLE
Why does Nanoc compile things twice?

### ISSUE THREAD

**Issue by RubenVerborgh** [nanoc/nanoc#1002]
Nanoc seems to compile items twice.

### Steps to reproduce

1. `nanoc create-site test && cd test`
2. Add `puts "compiling #{item.identifier}"` under line 3 in `Rules`
3. `nanoc co`

### Expected behavior

The compilation rule only triggers once.

### Actual behavior

The compilation rule triggers twice, as evidenced by the output:

```bash
$ be nanoc co
Loading site… done
Compiling site…
compiling /index.html
compiling /index.html
      create  [0.01s]  output/index.html
      create  [0.00s]  output/stylesheet.css

Site compiled in 0.03s.
```

**Comment by ddfreyne** [comment]
The rule is intentionally triggered twice. Both times, the rule is evaluated with proxy objects, so that no _actual_ compilation happens, but the intended actions are recorded. The recorded actions drive the compilation. For details, check out `RecordingExecutor` and the `ProcessingAction` subclasses. 

The reason why the recording happens twice is so that the item rep path can be referenced in a compilation rule. This wasn’t possible before v4.3.6, but #964 fixed that.

Eventually, a description of this process will end up on the [Internals](http://nanoc.ws/doc/internals/) page…

**Comment by ddfreyne** [comment]
Oh, forgot to mention. The reason for recording actions first is twofold:

* Be able to identify relevant changes to the `Rules` file to prevent unnecessary recompilation

* Decouple the `Rules` file a bit more from the actual compilation process, so that it becomes more realistic to use a different approach for providing processing instructions to Nanoc.

I’ll close this issue for now, as I believe it’s been resolved.

**Comment by RubenVerborgh** [comment]
That explains things, thanks a lot!

Was just a question BTW, not an actual bug. I assumed there was a good reason.

**Comment by ddfreyne** [comment]
I prefer to use GitHub only for issues, and have discussions/support requests/questions… on the [discussion group](https://groups.google.com/forum/#!forum/nanoc).
