### ISSUE TITLE
link_to causes "expected a string or an item, not a Nanoc::Identifier" error after upgrade

### ISSUE THREAD

**Issue by mwickens** [nanoc/nanoc#1072]
I'm getting an error when compiling after upgrading to Nanoc 4: 

> ArgumentError: Cannot link to <Nanoc::Identifier type=legacy "/doc/admin/01_about/01_intro/"> (expected a string or an item, not a Nanoc::Identifier)

I thought I'd followed all the upgrade instructions correctly. Here is a snippet of the code containing the `link_to` that's generating the error:

```
		<% chapters = ['01_about',
			'02_install',
			'03_basics',
			'04_gm',
			'05_user',
			'06_rules',
			'07_sysadmin',
			'08_report',
			'09_log',
			'10_backup',
			] %>
		<% chapters.each do |c|  %>
			<% chapStartRegex = Regexp.new(c + '\/01_intro\/$') %>
			<% itm = @items.find { |i| i.identifier =~ chapStartRegex} %>
			<p class="toc_1">
				<%= link_to(itm[:ChapterTitle], itm.identifier) %>
			</p>
			<%= chapter_contents('admin', c) %>
		<% end %>
```

Hopefully, I'm just missing something.

[crash.log.txt](https://github.com/nanoc/nanoc/files/714620/crash.log.txt)

**Comment by ddfreyne** [comment]
Replace

```rhtml
<%= link_to(itm[:ChapterTitle], itm.identifier) %>
```

with either

```rhtml
<%= link_to(itm[:ChapterTitle], itm.path) %>
```

or, even shorter,

```rhtml
<%= link_to(itm[:ChapterTitle], itm) %>
```

This will create the link to the given item, using the path (rather than the identifier) of the item. Routing rules might route items to a path that isn’t necessary the same as the identifier.

(You can use `nanoc check internal_links`, or `nanoc check ilinks` for short, to verify that all internal links are still valid.)

* * *

FYI, you can replace

```rhtml
<% itm = @items.find { |i| i.identifier =~ chapStartRegex} %>
```

with

```rhtml
<% itm = @items[chapStartRegex] %>
```

It behaves the same, and is a bit shorter.

**Comment by mwickens** [comment]
Thanks!
