### ISSUE TITLE
Compilation fails when cache directory exists (sometimes)

### ISSUE THREAD

**Issue by agross** [nanoc/nanoc#1094]
Nanoc compilation sometimes fails unless you `rm -rf tmp`.

### Expected behavior

Compilation succeeds.

### Actual behavior

Compilation fails.

### Details

The item reported in the log below is passed-through, no filters and such. Note the path pointing to a temporary file.

### Crash log

https://gist.github.com/agross/9831ab6eb3844783424b19f64bd7831c

**Comment by ddfreyne** [comment]
I’m unsure how to reproduce this. Can you try whether the issue also exists on `master`, and if so, could you provide a reproduction (a small one is preferred, but not required).

**Comment by agross** [comment]
I'll try to. I think I can reproduce it locally pretty reliably, but the project is rather complex.

**Comment by sunshineco** [comment]
This failure looks remarkably similar to the failure mentioned tangentially in #1082. I came up with a reproduction [recipe](https://github.com/nanoc/nanoc/issues/1082#issuecomment-278469639), but it only manifested when some in-progress patches from Denis were applied. However, if the underlying cause is the same, perhaps those patches and the recipe I provided could help track down the problem (assuming it still manifests on `master`).

**Comment by ddfreyne** [comment]
Any reproductions that work with `master` would be incredibly valuable!

I know that @gpakosz is also experiencing this issue.

**Comment by ddfreyne** [comment]
I have a reproduction case!

**Comment by ddfreyne** [comment]
A (WIP) fix is in #1109.

**Comment by agross** [comment]
Works for me! Many thanks!
