### ISSUE TITLE
Touching an item leads to recompilation

### ISSUE THREAD

**Issue by blinry** [nanoc/nanoc#1095]
When touching a file without changing its content, I'd expect nanoc to skip it.

### Steps to reproduce

```
$ nanoc --version
Nanoc 4.6.1 © 2007-2017 Denis Defreyne.
Running ruby 2.4.0 (2016-12-24) on x86_64-linux with RubyGems 2.6.8.
$ nanoc create-site test && cd test
      create  nanoc.yaml
      create  Rules
      create  content/index.html
      create  content/stylesheet.css
      create  layouts/default.html
Created a blank nanoc site at 'test'. Enjoy!
$ nanoc --verbose
Loading site… done
Compiling site…
      delete  output/
      create  [0.00s]  output/stylesheet.css
      create  [0.00s]  output/index.html

Site compiled in 0.01s.
$ touch content/index.html 
$ nanoc --verbose
Loading site… done
Compiling site…
   identical  [0.00s]  output/index.html
        skip  output/stylesheet.css

Site compiled in 0.01s.
```

### Expected behavior

nanoc skips the item /index.html, because it notices that its attributes and content have not been changed.

### Actual behavior

nanoc recompiles the item /index.html.

### Details

In a larger project, I noticed that when changing the content of an item, other items depending on its attributes (only) were recompiled (to identical files, because the attributes were not changed). I'd like to speed this up, but maybe I'm misunderstanding how dependencies as described [here]( https://nanoc.ws/doc/internals/) work.

**Comment by ddfreyne** [comment]
This is expected, as the filesystem data source adds a `:mtime` attribute, which will have changed when touching.

The proper solution for the incorrectly triggered outdatedness due to dependencies would be for Nanoc to track dependencies on a per-attribute basis, so that unused attributes won’t trigger outdatedness.

(The thought to adding a config option to the filesystem data source to disable `:mtime` crossed my mind, but that’s a poor workaround.)

**Comment by blinry** [comment]
Thanks!

**Comment by ddfreyne** [comment]
The new Nanoc 4.7.4 release improves this, as it will cause attribute dependencies to be only triggered if *relevant* attributes have changed.
