### ISSUE TITLE
Programmatically changing the content of an item does not cause outdatedness

### ISSUE THREAD

**Issue by th-h** [nanoc/nanoc#1220]
Nanoc won't re-compile items whose content has changed (e.g. due to time-related embedded code) as long as the file itself (its filesystem attributes) doesn't change. (See #1216 for a related issue.)

### Steps to reproduce

* Create a HTML/ERB file `/index.html` displaying the current time:
    ```
    <!DOCTYPE html>
    <html><head><title>Test</title></head>
    <body><p>Current date and time: <%= Time.now.strftime('%d.%m.%Y %H:%M') %></p></body>
    </html>
    ```

* Compile the site

* Wait one or two minutes

* Compile the site again

### Expected behavior

The `/index/` item should be updated after the second compile and containt the current time.

### Actual behavior

The `/index/ `item is never updated (after the first compile).

### Details

You have to update the `mtime`: `touch content/index.html` After that, the item will be updated once, but stay unchanged until you `touch` it again.

Nanoc doesn't pick up that the content has changed.

**Comment by ddfreyne** [comment]
This is not a bug, but expected behavior.

Nanoc does not track dependencies on global state. This includes, among others:

* The current date/time (e.g. `<%= Time.now %>`)
* Environment variables (e.g. `<%= ENV['PATH'] %>`)
* Data read directly from the filesystem (e.g. `<%= File.read('content/about.md') %>`)
* Data read over the network
* Global variables (e.g. `<%= $0 %>`)
* Data obtained from invoking other programs (e.g. ``<%= `ruby --version` %>``)

The recommended approach to ensure dependencies are tracked properly, is to stick the content in `@config` during preprocessing, e.g.

```ruby
preprocess do
  @config[:now] = Time.now
end
```

… and then use it later, when needed:

```rhtml
<p>
  Current date and time:
  <%= @config[:now].strftime('%d.%m.%Y %H:%M') %>
</p>
```

**Comment by ddfreyne** [comment]
Also see nanoc/nanoc.ws/issues/148, a documentation issue I’ve sadly been neglecting.

**Comment by th-h** [comment]
So that changed with Nanoc 4x.? (Or worked in 3.x just by accident?)

**Comment by ddfreyne** [comment]
@th-h It worked by accident in 3.x.
