### ISSUE TITLE
Sassc support?

### ISSUE THREAD

**Issue by moll** [nanoc/nanoc#1343]
Hey,

Given that Sass's Ruby implementation is deprecated in favor of its C implementation (sassc), is there a plan to have it supported by Nanoc? I noticed there were [two sentences](https://gitter.im/nanoc/nanoc?at=5abccf57e3d0b1ff2c7de2ec) of it in the Gitter Nanoc chatroom, but that was about.

Thanks!

**Comment by ddfreyne** [comment]
Hi,

Sassc support is not currently available, but it is something I’d like to have. The main area of difficulty is integrating it with Nanoc’s dependency tracker; while this was somewhat easy with Ruby Sass, it might be difficult (or impossible) to do with non-Ruby Sass implementations.

For example, given:

* /assets/style/_fonts.css
* /assets/style/screen.css

Assuming that `screen.css` imports `_fonts.css`, then Nanoc needs to know that there is a dependency, so that if `_fonts.css` changes, Nanoc knows to recompile `screen.css`.

Some ideas I have around making this work:

* Be able to mark items as “always dirty” — and therefore always recompiled, no matter what. Not so nice, but a workable last resort.

* Use the generated sourcemaps to identify dependencies (likely possible with Dart Sass, unsure about LibSass).

I’ve moved this into nanoc/features/issues/45.
