### ISSUE TITLE
Rebuilding the site when environnement variable is changed

### ISSUE THREAD

**Issue by Doshirae** [nanoc/nanoc#1364]
My setup on my local machine and on my server is a bit different, so I have to update links if I build for local or for production 

I do that with a `PROD` env-var that I set to true when I want to build for my server
And in my layouts, I have tests to check that variable, and modify links accordingly
A little exemple : 

```erb
# in layout/post.erb
	<% path = @item.path %>
	<% if ENV["PROD"] == "true" %>
	<% path = path.split("/") %>
	<% path.delete_at(1) %>
	<% path = path.join("/") %>
	<% end %>
	<h2><%= link_to @item[:title], path %></h2>
```

But when I execute nanoc, it doesn't care

```zsh
~/permanent/web
% bundle exec nanoc
Loading site… done
Compiling site…

Site compiled in 0.66s.


~/permanent/web
% PROD=true bundle exec nanoc
Loading site… done
Compiling site…

Site compiled in 0.66s.
```

I would expect it to update the files, because the content clearly changes whether I activate that variable or not.

Is that a normal behavior or not ?
I thought at first I was doing something too complicated for nanoc but now I don't think so (and I love nanoc so I don't wanna use anything else)

**Comment by ddfreyne** [comment]
> Is that a normal behavior or not ?

It is normal and expected behavior… but not desired. Let me elaborate!

Nanoc tracks data and detects changes, and knows which items to recompile and which ones not to recompile. However, it can only track data _that it knows about_, and it cannot track changes to global state.

The following kinds of data are _not_ tracked by Nanoc:

* Global variables (e.g. `<%= $foo %>`)
* Constants (e.g. `<%= RUBY_VERSION %>`)
* The environment (e.g. `<%= ENV["PROD"] %>`)
* The filesystem (e.g. `<%= File.read('oink.txt') %>`)
* Time-related data (e.g. `<%= Time.now %>`)
* Random data (e.g. `<%= rand(1..10) %>`)
* Dynamically evaluated data (e.g. ```<%= `ruby --version`.strip %>```)
* … and possibly more

It is not feasible for Nanoc to track global state. (More details near the bottom of this text.)

Global state creates other problems with Nanoc, too. For example, it is possible to get `NoMethodError`s when using global variables; see the [Nanoc objects are stored in global variables](https://nanoc.ws/doc/troubleshooting/#nanoc-objects-are-stored-in-global-variables) troubleshooting section for an idea.

## Working around the problem

To work around this, use the preprocessor to populate the configuration (`@config`), e.g.

```ruby
preprocess do
  config[:is_prod] = ENV['PROD']
end
```

… and where-ever you’d use `ENV['PROD']`, use `@config[:is_prod]` instead, e.g.

```rhtml
	<% path = @item.path %>
	<% if @config[:is_prod] == "true" %>
	<% path = path.split("/") %>
	<% path.delete_at(1) %>
	<% path = path.join("/") %>
	<% end %>
	<h2><%= link_to @item[:title], path %></h2>
```

## Solving the problem

Tracking global state is a fundamentally difficult problem, and it is a problem that will not go away any time soon either. Solving it on Nanoc’s site is infeasible, however:

* To track global variables, Nanoc would have to intercept global variables access somehow in the Ruby VM. Unlikely to be possible.

* To track constants, Nanoc could replace all constants with functions that notifies Nanoc and then return the original constant value

* To track the environment, Nanoc could replace `ENV` with its own implementation that notifies Nanoc when data in it is accessed.

* etc…

I for sure would not want to run software that does this kind of hacky stuff. :)

I thought about letting Nanoc do static analysis on items and layouts to find out whether global state is being accessed, but doing that in a remotely reliable way is, as far as I can tell, impossible.

So, we’re stuck with the problem and all we can do is learn how to live with it!

A next step for me is to document this problem in more detail on the Nanoc web site. I’ve been aware of it (hence the link above), but it needs even more documentation.

Hope this helps!

**Comment by Doshirae** [comment]
The preprocess trick really does the job :)

Thanks a lot for the insights !

**Comment by ddfreyne** [comment]
I’ve created a troubleshooting section for this problem: https://nanoc.ws/doc/troubleshooting/#pages-are-not-being-recompiled

**Comment by Fjan** [comment]
@Doshirae Just thought I should point out that the "proper" way to solve this is by using the environment support built into nanoc. You would simply use `ENV["NANOC_ENV"] == 'production'` instead of `ENV["PROD"]==true` and then compile with `nanoc --env=production`. Nanoc keeps a separate set of dependency state for each environment in that case and it should work as expected. It's also much faster than the pre-processing trick mentioned on the troubleshooting section because it doesn't have to recompile the entire site.

@ddfreyne Perhaps this should be mentioned in the troubleshooting section too?

**Comment by Doshirae** [comment]
I tried ^^
It didn't work :/

Le 24/10/18 - 02:16, Jan M. Faber a écrit :
> @Doshirae Just thought I should point out that the "proper" way to solve this is by using the environment support built into nanoc. You would simply use `ENV["NANOC_ENV"] == 'production'` instead of `ENV["PROD"]==true` and then compile with `nanoc --env=production`. Nanoc keeps a separate set of dependency state for each environment in that case and it should work as expected. It's also much faster than the pre-processing trick mentioned on the troubleshooting section because it doesn't have to recompile the entire site.
> 
> @ddfreyne Perhaps this should be mentioned in the troubleshooting section too?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/nanoc/nanoc/issues/1364#issuecomment-432579850

-- 
Doshirae
My GPG key is available here: https://data.doshi.re/doshirae.asc

**Comment by Fjan** [comment]
Hmm, ok, I'm doing something very similar in my nanoc app without any issues. I should probably point out that you need to define the two environments 'production' and 'default' in the nanoc.yaml file for them to be picked up.
