### ISSUE TITLE
Link checker no longer understand protocol relative URLs

### ISSUE THREAD

**Issue by Fjan** [nanoc/nanoc#1442]
The internal link checker fails on protocol relative URLs

### Steps to reproduce

1. Use a protocol relative link, for example:

 `<script src="//ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>`
2. nanoc compile 
3. nano check ilinks

### Expected behavior

Running check internal_links…   ok

### Actual behavior

output/index.html:
    [ ERROR ] internal_links - broken reference to file://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js

### Details

This bug seems to be introduced here: https://github.com/nanoc/nanoc/commit/d98ab4636aeeb80c3f6c4e71c166a6744eaaa9c5

**Comment by ddfreyne** [comment]
@da2x Is this something you could/want to look into?

**Comment by da2x** [comment]
It’s working as expected, the relative protocol scheme you’re relative to when checking is indeed `file:`.

The link checker doesn’t know your base URI so it’s using the context default URI (which isn’t http: or even https:). Open a new tab and type `//ajax.googleapis.com/` into the address field. Most (if not all) web browsers will resolve it to `file:///ajax.googleapis.com/` by default.

When referencing external resources, you always should include the protocol scheme. Loading a page with that link from a `file:`, `read:`, `data:`, `ipfs:`, `dat:`, `about:`, or any other protocol would yield a broken link. 

If this behaviour is undesired then we could change the link checker to parse URIs relative to the `base_url` setting instead of Nanoc’s output directory. I’m not sure how many users set this option, though.

You can override the default URI on the web platform by expressly setting the document’s protocol scheme using the `<base href="https://www.example.com/">` element. Unfortunately, this is **not** supported by Nokogiri::HTML; which the link checker relies upon when extracting links from documents. Adding base elements to your documents, and fixing this issue in Nokogiri would be the correct way to get this working if you really want to keep using protocol-relative links in your documents.

**Comment by Fjan** [comment]
Well I wouldn't say it's working as expected 🙂. Almost everyone is using nanoc to build a site that works on the http or https protocol, so the fact that your script chose file:// to check the links seems unexpected to me. I understand that choice is made since it's easier to check for existence of a file than to start up a web server and check through there, but that's an implementation artefact that the user shouldn't be bothered with.

More to the point, a protocol relative link is an **external** link, and this bug report is for the **internal** link checker, so I think for the purpose of the internal link checker it should simply ignore them. 

(I haven't tried out the external link checker, but I assume that uses a real web call instead of checking existence of a file so the problem shouldn't arise there. If it does you should probably open another issue)

**Comment by ddfreyne** [comment]
Protocol-relative URLs were explicitly supported before, and should keep on being supported, so this is a bug.

It’s a bit tricky to make the `external_links` check handle this properly. I think the check can assume that the protocol is either `http` or `https`, rather than `file`, so `//example.com/foo` could/should be interpreted as `http://example.com/foo`. (I’d rather go with `http` as the default, rather than `https`.)

**Comment by ddfreyne** [comment]
(And the internal links checker should ignore this type of URL indeed.)

**Comment by ddfreyne** [comment]
I started working on a fix in #1444.

**Comment by ddfreyne** [comment]
Fix released in 4.11.7.
