### ISSUE TITLE
Autolink

### ISSUE THREAD

**Issue by cup** [nanoc/nanoc#1478]
Autolink is supported by RedCarpet:

https://github.com/vmg/redcarpet

but how to enable it with Nanoc?

**Comment by ddfreyne** [comment]
See the [Redcarpet filter documentation](https://nanoc.ws/doc/reference/filters/#redcarpet): you can pass options through to Redcarpet via the `options` hash:

```ruby
filter :redcarpet, options: { autolink: true }
```

For questions, it is best to ask the [Nanoc discussion group](https://groups.google.com/forum/#!forum/nanoc) rather than opening an issue here — you’ll get better feedback there, and GitHub issues is focused on issues rather than support.

Hope this helps!
