### ISSUE TITLE
nanoc-core gem implicitly depends on nanoc gem via version_information

### ISSUE THREAD

**Issue by boutil** [nanoc/nanoc#1661]
Hi,
the method `version_information` from `nanoc-core/lib/nanoc/core.rb` tries to load `Nanoc::VERSION`, which is defined in the `nanoc` gem.

In the (very unlikely) scenario, when `nanoc-core` is installed without nanoc, trying to read Nanoc::Core.version_information would fail because of `Nanoc::VERSION` undefined.

We have the problem in Debian when we run the tests, without bundler.
Requiring "nanoc/version" from "lib/nanoc/core.rb" solves the issue in a hacky way, and creates an explicit dependency loop.

I was wondering if you were aware of this minor issue, and if you had a way to circumvent it.

**Comment by denisdefreyne** [comment]
Oh, that was a mistake on my part, likely in the process of moving implementation bits into `nanoc-core`.

I made a fix, 2266bb1b463bb014c45a4ebaeedf90da3b92dc74, which uses `Nanoc::Core::VERSION` instead of `Nanoc::VERSION`. These version numbers are always in sync (there are tests for this), so this fix should be correct.

Can you let me know whether this works for you?

**Comment by boutil** [comment]
This works perfectly, thanks!

**Comment by denisdefreyne** [comment]
This is fixed in the most recent Nanoc release.
