### ISSUE TITLE
Workflow control / Multipass generation

### ISSUE THREAD

**Issue by grv87** [nanoc/nanoc#527]
I need to generate a webpage with a subject index (like in the book, but for website). Items of the index aren't known beforehand and are registered by a helper. After the creation of the list of items I'm able to generate the whole index.

However, filter can be applied on the compile stage only, and new pages can't be created there. I see that I need either more sophisticated workflow or multipass generation.

Can that be done in nanoc? Maybe with use of hooks?

**Comment by DivineDominion** [comment]
I guess you use a filter to collect information because it can be applied to every existing item when they're touched anyway: during compilation. You can loop over all items in your entire site, too, and collect data before compilation. Then you wouldn't need a filter.

I have a tag index on my website. I put the generation into the `preprocess` block in Rules.rb:

```
preprocess do
  My::Environment::setup_environment(site)

  items.delete_if { |item| item[:publish] == false }

  def tag_worklog
    tags = all_tags
    
    tags.each do |tag|
      @items << Nanoc::Item.new(
        "",
        {
          :title => %Q{Posts tagged &ldquo;#{tag}&rdquo;},
          :tag => tag,
          :mtime => Time.now#parse(Date.now) # for the sitemap
          # TODO ^-- this is the wrong mtime actually, it should be the time of the last item change
        },
        "/posts/tags/#{tag}"
      )
    end
    
    @site.tags = tags
  end

  tag_worklog
end
```

The actual `all_tags` method is a helper method in `lib/`:

```
def all_tags
  posts = sorted_posts
  tags = Set.new # unique items only
  
  posts.each do |post|
    post[:tags].each do |tag|
      tags.add(tag)
    end unless post[:tags].nil?
  end
  
  return tags.to_a.sort
end
```

This creates items on the fly before compilation, so it's possible to use compile and routing rules on the items just as if they were file-based:

```
compile '/posts/tags/' do
  # tag index *is* a file, actually, looping over all tags
end

compile '/posts/tags/*/' do
  # this matches the items we've just created
end
```

**Comment by grv87** [comment]
Thank you for the answer.

Unfortunately, this approach don't work in my case, since items for the index are defined in the text, not in the metadata. I can't use `post[:tags]` to get items for the index. I use helper that logs items and also creates `<a id=...>` HTML tags. (Firstly I wrote filter, it's actually helper). I could write custom parser and use it in the `preprocess` stage, but I look for a simpler way.

The same problem exists in LaTeX which uses `makeindex` for the generation of index. For the full build it requires several runs. First updates index file, second incorporates created file. If in the second generation index file is changed, then there is third generation and so on, until everything stabilizes. Now I see that I can try to emulate this behavior using `guard`. I'll try it, but it would be good if this would work from the box.

**Comment by DivineDominion** [comment]
Ah well, if it's in the contents, then I understand why you'd need something similar to LaTeX's makeindex indeed!

**Comment by ddfreyne** [comment]
There’s no easy way to do this in nanoc, because what you’d like to achieve doesn’t fit in nanoc’s conceptual compilation flow, where new items cannot be created after compilation has started.

I’d suggest creating a separate rake task for generating the index. A full compilation would then invoke nanoc, the index generation script, and nanoc again, pretty much the way LaTeX would do it.

This is something I’d like to address for nanoc 4.

**Comment by ddfreyne** [comment]
Also, please use the [nanoc forum](https://groups.google.com/forum/#!forum/nanoc) to get support. GitHub Issues is dedicated purely to issues and pull requests.

I’ll close this issue here for now.
