### ISSUE TITLE
How can I plug my method on before/after site compilation?

### ISSUE THREAD

**Issue by igorspasic** [nanoc/nanoc#531]
I need to perform some data statistics on all inputs. And need to write summary file at the end. Filter does not help, as it is not aware of start/end. So far, Ive added an property in site config to detect the 'before' event, but don't have a trick for the 'after' event.

More details: I would like to reach item content AFTER applying kramdown, but BEFORE the template is applied. I could store this content in items hash, but still dont know how to be sure to catch things in the right moment.

**Comment by ddfreyne** [comment]
It seems your issue is quite similar to #527. Calculating the statistics and writing a summary can’t be done with a filter, since after compilation has started, no new items can be generated. I’d suggest moving the statistics calculation into its own Rake task, and run it separately from nanoc.

Also, please use the [nanoc forum](https://groups.google.com/forum/#!forum/nanoc) for support requests. GitHub issues is intended to be used for filing bugs. I’ll close this issue here for now, but please do continue the conversation on the forum.
