### ISSUE TITLE
Feature request: Finer-grained dependency tracking

### ISSUE THREAD

**Issue by jugglinmike** [nanoc/nanoc#541]
Would it be possible for nanoc's dependency tracker to make a distinction between item contents and item attributes? In other words: can nanoc recognize when a representation only depends on an item's attributes so that even when item content changes, that representation is not re-compiled?

### Example use case:

I'm working on a site that offers content in a few languages. For pages with multiple translations, I would like to render links to the alternate versions. One way I've prototyped this is through an item attribute named `canonical`.

- `content/hello.md`

        ---
        ---
        Hello.
- `content/pt-br/ola.md`

        ---
        canonical: /hello/
        ---
        Ola.
- `content/es-mx/hola.md`

        ---
        canonical: /hello/
        ---
        Hola.

With this setup, I can create a hash of identifiers in a `preprocess` block and store it as a `:locales` attribute on the "canonical" item. I can then access this from a layout generally via code like:

```erb
<%
canonical = @item[:canonical] ? @items[@item[:canonical]] : @item
canonical[:locales].each { |lang, id|
  render("locale_link.md", :lang => lang, :id => id)
}
%>
```

The problem here is that nanoc's dependency tracker (correctly) detects that I am referencing the "canonical" item, and it registers this as a dependency. Now, whenever the "canonical" version's *content* changes, the localized representations are needlessly re-compiled.

This is not so bad, except that I would also like to use this mechanism to generate static links in a generic "header" layout shared between most pages on my site:

```erb
<%
link_text = translate("contact")  # defined elsewhere (not directly relevant)
current_locale = @item[:locale]   # (inferred from item identifier)
contact_href = @items['/contact/'][:locales][current_locale]
%>
<nav id="site-main-menu">
  <a href="<%= contact_href %>"><%= link_text %></a>
  <!-- (additional navigation links here) -->
</nav>
```

If I re-use this across the site, then any change to the *content* of the `/contact.md` item will trigger recompilation of every page. This is the behavior I would like to avoid.

---

My use case is obviously far more specific than the feature request suggests. I've tried to propose a solution that makes sense for nanoc generally outside of this context. That said, I'm very open to suggestion for other ways to avoid this problem. If I can do this with nanoc's current features (maybe there's a better way to structure my content?), then that would obviously be ideal. It might also be the case that there are alternative ways to extend nanoc that would help me here (for instance, defining a public API for the dependency tracker so I could express this relationship explicitly).

Thanks for the great tool!

**Comment by ddfreyne** [comment]
This issue is definitely on the radar to be fixed, although I don’t think it’ll ever land in nanoc 3.x. There are a few issues related to dependency tracking which I’d like to fix in 4.0. Here’s some Trello tickets:

* [Efficient outdatedness checking](https://trello.com/c/AVIuz24Z/33-efficient-outdatedness-checking)
* [Improved dependency tracking](https://trello.com/c/2pd0LJ9R/64-improved-dependency-tracking)
* [Make adding items not cause entire site to be recompiled](https://trello.com/c/19zdXx7e/62-make-adding-items-not-cause-entire-site-to-be-recompiled)

Some of these overlap in some way. There is also the fine-grained dependency tracking based on attributes, which I think isn’t yet codified in any Trello card (strangely enough).

I did take a stab at implementing fine-grained dependency twice in nanoc 3.x, and it’s really quite difficult to get right. The algorithm, which already is complex, becomes even more complex. Because of this, I’d like to tackle it in nanoc 4.x, where there’s no requirement to remain backwards compatible in any way.

As for nanoc 4.x… even though I haven’t touched it in a while, it’s not a cancelled project. I’m taking a break. There are some fundamental issues that I’d like to solve, and I haven’t really had the energy to start working on that.

**Comment by ddfreyne** [comment]
Didn’t mean to close this, but I suppose it’s not a bad thing. I’ll link to this issue from a new Trello card.

**Comment by ddfreyne** [comment]
This now lives [in this Trello card](https://trello.com/c/sfQSEdmJ/75-fine-grained-dependency-tracking).
