### ISSUE TITLE
New Check Proposal: Link protocol

### ISSUE THREAD

**Issue by jugglinmike** [nanoc/nanoc#542]
We've recently purchased an SSL certificate for serving our nanoc-powered site. I'd like to avoid mixed content warnings by ensuring all embedded content is specified with a secure protocol or a protocol-relative URL. In order to prevent regressions, I'd like to implement an automated test for this.

This seems in line with nanoc's current checks--would a patch implementing `nanoc check secure-links` (or similar) be considered?

**Comment by ddfreyne** [comment]
A good idea!

This shouldn’t be too difficult to implement. Off the top of my head, I think the following changes will need to be made:

* The existing links collector will probably need to be updated to capture some context (`img src`, `a href`, `link href`, …) so that it can restrict itself to included resources only.

* The base URL will need to be set in the site configuration so that the checker knows whether a URL is acceptable.

**Comment by ddfreyne** [comment]
You can take a stab at implementing this if you want!
