### ISSUE TITLE
Better consistensy between Filesystem and Nanoc::Identifier (Nanoc 4.x)

### ISSUE THREAD

**Issue by barraq** [nanoc/nanoc#664]
`Nanoc::Filesystem` currently provides one of the following options: `allow_periods_in_identifiers`. As said in the documentation:

    # Whether to allow periods in identifiers. When turned off, everything
    # past the first period is considered to be the extension, and when
    # turned on, only the characters past the last period are considered to
    # be the extension. For example,  a file named “content/about.html.erb”
    # will have the identifier “/about/” when turned off, but when turned on
    # it will become “/about.html/” instead.
    allow_periods_in_identifiers: false

When using this option with the `full` identifier the behavior of Nanoc::Identifier is to my point of view misleading: let me explain. Let `toto.html.haml` be a file in your filesystem.
Suppose that you have the following rule:

```ruby
route '/toto.*' do
  puts item[:extension]
  puts item.identifier
  puts item.identifier.with_ext('html')
  '/toto.html'
end
```

The following is outputted

```shell
html.haml
/toto.html.haml
/toto.html.html
```

Therefore

- item[:extension] returns `html.haml` which is what is expected
- item.identifier returns `/toto.html.haml` which is what is expected in `full` mode
- however `item.identifier.with_ext('html')` returns `toto.html.html` which is not what I expect when using the `allow_periods_in_identifiers=false` since  item[:extension] returns `html.haml`. It would be better if it returned `toto.html` therefore using:

    ```ruby
    # Returns a regex that is used for determining the extension of a file
    # name. The first match group will be the entire extension, including the
    # leading period.
    def extension_regex
      if @config && @config[:allow_periods_in_identifiers]
        /(\.[^\/\.]+$)/
      else
        /(\.[^\/]+$)/
      end
    end
    ```
Maybe the option `allow_periods_in_identifiers` lose some meaning when in `full` identifier mode but then it would be really cool to provide another option so that we can use:  `item.identifier.with_ext('html')` in a way that is coherent with what item[:extension] returns.

What do you think ?

Best

**Comment by ddfreyne** [comment]
Yeah, definitely something fishy going on here… I think `allow_periods_in_identifiers` should be considered to be `false` when for full identifiers.

**Comment by ddfreyne** [comment]
I’ll think about this a bit more though.

**Comment by barraq** [comment]
@ddfreyne should not the Nanoc::Identifier module (for an Item) be relying on the Nanoc::FileSystem module (to which this Item belong) to manipulate extension ? 

- Nanoc::Identifier.with_ext
- Nanoc::Identifier.without_ext
- Nanoc::Identifier.ext

That way all the logic will be in one place: Nanoc::FileSystem

**Comment by ddfreyne** [comment]
I’m a bit torn on what the correct behavior should be. For example, Ruby’s built-in method for getting the extension of a filename (which is used by `Nanoc::Identifier`) does not take multiple extensions into account:

```ruby
File.extname('toto.html.haml')
# => ".haml"
```

I could let `Nanoc::Identifier` take an option that determines whether or not the identifier is treated as having potentially multiple extensions. For instance:

```ruby
Nanoc::Identifier.new('/toto.html.haml', multiple_extension: true).ext
# => 'html.haml'
Nanoc::Identifier.new('/toto.html.haml', multiple_extension: false).ext
# => 'haml'
Nanoc::Identifier.new('/toto.html.haml').ext
# => 'haml'
```

This approach feels a little strange since this effectively moves the configuration inside the individual identifiers, meaning that different identifiers can have different behaviors in this regard.

The current `allow_periods_in_identifiers` configuration option is part of the filesystem data source. This means that different data sources can (even in nanoc 3) return identifiers that look differently.

`Filesystem` is one of potentially many data sources, so letting `Nanoc::Identifier` depend on the behavior in `Filesystem` is not realistic.

This inconsistency would remain in nanoc 4, and would get more subtle (identifiers look the same, but don’t behave the same), which I believe is worse.

The `allow_periods_in_identifiers` configuration option could be moved out of the data source config into the global config. This is tricky because identifiers then need a reference to the site configuration, which is hard to provide at the time of construction, and adds another dependency, which complicates things and will eventually lead to confusion.

An alternative could be to let the `#with_ext` and `#without_ext` methods take a param that determines whether or not all extensions should be considered:

```ruby
Nanoc::Identifier.new('/toto.html.haml').with_ext('html', multiple_exts: false)
# => 'html.haml'
Nanoc::Identifier.new('/toto.html.haml').with_ext('html', multiple_exts: true)
# => 'haml'
Nanoc::Identifier.new('/toto.html.haml').with_ext('html')
# => 'html.haml'
```

In order to minimise confusion, I’d let the combination of `allow_periods_in_identifiers` + full identifiers raise an exception.

Does this sound reasonable?

**Comment by barraq** [comment]
The last proposition seems reasonable to me. However did you mean:

```ruby
Nanoc::Identifier.new('/toto.html.haml').with_ext('html', multiple_exts: false)
# => '/toto.html.html'
Nanoc::Identifier.new('/toto.html.haml').with_ext('html', multiple_exts: true)
# => '/toto.html'
Nanoc::Identifier.new('/toto.html.haml').with_ext('html')
# => '/toto.html'
```

Also to make `item[:extension` consistent with `item.identifier.ext` I believe that the option *multiple_exts* should be true for both: `without_ext, with_ext, ext`. What do you think ? I know that this might break things for old websites.... but who is using double extensions on his files without using these double extensions ? I mean I think that all users that have files with double extensions do it with the same purpose: they use one ext for the kind (md, haml, erb, etc.) and one ext for the output extension (html, xml, etc.). Therefore introducing this new feature will help them in this process; the other users (those using single ext) will not be affected anyway.
 
In addition to all of that, in my websites I am using an home made method to cope with two parts extensions: 

```ruby
# Split a file `extension` into a two parts `ext` and `kind` where
# `ext` is the output file extension (e.g. html, xml, etc.) and `kind`
# is the input file extension (e.g. md, html, etc.).
#
# @param [String] extension is the file extension, e.g. `html.md`, `xml`.
# @param [String] default is the default output extension if none is specified.
#
def split_ext(extension, default: nil)
  ext, kind = extension.split('.')
  [if kind then ext else default end, kind || ext]
end
```

I use it as follow in my *compile* rules:

```ruby
ext, kind = split_ext(item[:extension], default: 'html')
case kind
when ...
end
```

maybe `split_ext` can be added to Nanoc::Identifier too.

Best,
Rémi

**Comment by ddfreyne** [comment]
> However did you mean: [snip]

Yup. I’ll update the original content; my mistake!

Here’s an alternative approach:

* `#exts` method (returning a list of extensions)
* `#without_exts` (removes all extensions)

One could then replace all extensions using `without_exts.with_ext('html')`. It would make your `#split_ext` a little easier to implement (although it wouldn’t replace it completely).

The reasoning for this altnernative approach is that I find that the `multiple_exts` argument to `#with_ext` is confusing.

```ruby
Nanoc::Identifier.new('/toto.html.haml').without_exts.with_ext('html')
# => '/toto.html'

Nanoc::Identifier.new('/toto.html.haml').without_ext.with_ext('html')
# => '/toto.html'

Nanoc::Identifier.new('/toto.html.haml').with_ext('html')
# => '/toto.html.html'
```

The first and the second case are actually identically, because `#with_ext` changes the existing extension if one is present. Confusing, sadly.

**Comment by barraq** [comment]
Thanks Deny that is indeed much cleaner and clearer !
I like the `#exts` and `#without_exts` approach better, the functions names speak for themselves and therefore it is less error prone.

Regarding the the fact that 

```ruby
Nanoc::Identifier.new('/toto.html.haml').without_ext.with_ext('html')
```
returns 
```ruby
# => '/toto.html'
```
it is indeed confusing... would not it be better that `with_ext` does not change the extension but appends one ? Actually I thought it was the case until you told me it was not :)

**Comment by ddfreyne** [comment]
With the addition of `#without_exts` and `#exts`, and the removal of `#with_ext`, I think this issue is now solved. I’ll close it, but please do let me know if you think there’s still something unresolved!

**Comment by barraq** [comment]
Thanks @ddfreyne :+1:
