### ISSUE TITLE
Option to disable/filter kramdown warnings

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc#675]
kramdown spits out warnings that are not always very useful. For instance:

```
kramdown warning: No link definition for link ID 'git' found on line 4 
```

It would be useful to have an option to either disable warnings entirely, or filter them.

**Comment by gpakosz** [comment]
I started implementing warning filtering.

My idea was to store regexps inside `@config[:kramdown][warning_filters]` as an array. Later, I would filter with `filter :kramdown, @config[:kramdown] || {}`. Then inside the `:kramdown` filter implementation, I would use the `warning_filters` array.

At that point, I found it difficult to reliably store regexps inside `nanoc.yaml`. Should we use `!ruby/regexp` or store them as plain strings? If stored as plain strings, are there corner cases when trying to converting them to real regexps in order to filter Kramdown's `@warnings` array?

**Comment by ddfreyne** [comment]
> Should we use `!ruby/regexp` or store them as plain strings?

I think I prefer strings.

> If stored as plain strings, are there corner cases when trying to converting them to real regexps in order to filter Kramdown's `@warnings` array?

Not that I know of… `Regexp.new(string)` should work.
