### ISSUE TITLE
link_to seems to be calling "path" which seems to be undefined?

### ISSUE THREAD

**Issue by pitosalas** [nanoc/nanoc#684]
Line 49 in link_to.rb calls target.path.

I am getting an undefined method, and I don't know the code base well enough to determine if that's a bug or not.

**Comment by ddfreyne** [comment]
Same as #685 I believe.

**Comment by ddfreyne** [comment]
This is tricky to fix, because if `#link_to` receives `nil` (obtained from `@items[]` presumably), it doesn’t know what to link to.

A solution would be to let `@items[]` return a null object that remembers its criteria, but mimicking a null object is not something I would like to do in Ruby. :(

Thinking about leaving it as-is for now. This is not a bug in nanoc. @pitosalas If you disagree, please let me know and I’ll reopen the issue!
