### ISSUE TITLE
While migrating from Nanoc 3.x to 4.0.rc2 trouble with item.parent returns `Nil` for items with parent

### ISSUE THREAD

**Issue by laveesht** [nanoc/nanoc#690]
My problem goes like this,
item.parent is returning me `nil` even though is has a parent.

Was reading through the source , dint understand this comment,
"For items with identifiers that have extensions, returns nil."
https://github.com/nanoc/nanoc/blob/master/lib/nanoc/base/views/item_view.rb#L46

Need some help here.

**Comment by ddfreyne** [comment]
@laveesht Do you use the new identifier style? In other words, does your configuration file have `identifier_type: full`?

If so, then the parent for all items will be nil, since parents are no longer supported in nanoc 4 for new-style, “full” identifiers.

You can still fetch the parent of an item this way:

```ruby
@items[@item.identifier.to_s.sub(%r{/[^/]+\z}, '') + '.*']
```

The pattern generated this way matches any parents, e.g. for `/foo/bar.md` it would generate `/foo.*`.

**Comment by laveesht** [comment]
Yeah i was using `identifier_type: full` in configs.
Okay so `item.parent` is now removed.
Thanks for the regex , will try to work my way around somehow.
In any case is there any detailed docs of the core changes in nanoc somewhere , can you please point me there.

**Comment by ddfreyne** [comment]
There’s the [upgrade guide](http://v4.nanoc.ws/doc/nanoc-4-upgrade-guide/), but it apparently does not mention the parent change. Will fix; see nanoc/nanoc.ws#124.
