### ISSUE TITLE
v4.0 @item.parent is always nil, @item.children is always []

### ISSUE THREAD

**Issue by agross** [nanoc/nanoc#707]
Hey there,

the title says it all. Whenever I try to get an item's parent or its children, I either get `nil` or `[]` back. How can I help to resolve the issue?

Quick repo: I added this to the `nanoc create-site` `layouts/default.html`:

```diff
diff --git a/layouts/default.html b/layouts/default.html
index fe92627..2d6122f 100644
--- a/layouts/default.html
+++ b/layouts/default.html
@@ -10,6 +10,8 @@
   </head>
   <body>
     <div id="main">
+      <%= @item.children.inspect %>
+      <%= @item.parent.inspect %>
       <%= yield %>
     </div>
     <div id="sidebar">
```

It yields:
```html
    <div id="main">
      []
      nil
<h1>A Brand New Nanoc Site</h1>
```

**Comment by ddfreyne** [comment]
Items that use the new `identifier_type: full` rather than `identifier_type: legacy` do not have parents nor children. The child-parent relationship is ambiguous in some cases, such as here:

```
/foo.html
/foo.md
/foo/bar.md
```

The parent of `/foo/bar.md` is unclear, and so are the children of `/foo.html` and `/foo.md`.

In the past, I’ve used the following snippet to find the parent, although it does suffer from ambiguity. It replaces the last segment with a `.*` glob, and performs the find that way. It actually finds the first existing ancestor, which may or may not be what you want.

```ruby
def find_parent(identifier_string)
  parent_glob = identifier_string.sub(%r{/[^/]+\z}, '') + '.*'

  parent = @items[parent_glob]
  if parent
    parent
  elsif parent_glob != '.*'
    find_parent(parent_glob)
  else
    nil
  end
end
``

**Comment by ddfreyne** [comment]
Also see nanoc/nanoc.ws#124 — there is no documentation around this change, and it is causing confusion (as you know).

OK to close this ticket and retain nanoc/nanoc.ws#124?

**Comment by ddfreyne** [comment]
Also see #709—rather than returning useless data, these two methods should error.

I’ll close this ticket now, but feel free to comment if you believe the problem lies elsewhere.
