### ISSUE TITLE
Can I implement postprocessing?

### ISSUE THREAD

**Issue by gjtorikian** [nanoc/nanoc#711]
I'm curious to know if that'd be a useful addition. Which is a humble way of saying, "I need it, and I think others might need it too!" :grinning: 

Essentially a postprocess would occur *after* all compilation and purging. It would rerun when/if items changed. I'd probably take a peek at the implementation for preprocess and crib heavily from it.

**Comment by ddfreyne** [comment]
Having a post-process block has been on the wishlist for a while. The wiki page containing the archived Trello board even has a [Postprocess section](https://github.com/nanoc/nanoc/wiki/%5BARCHIVED%5D-nanoc-4-Trello-board#postprocess-block).

What’s your use case specifically?

A postprocess block could be as simple as a block that’s executed at the end. For instance:

```ruby
postprocess do
  @items.each do |item|
    $search_index.update(
      item.path,
      item.compiled_content(snapshot: :last),
    )
  end
end
```

This could be extended by letting item instances (and item rep instances) within the postprocess block have a `#updated?` and/or `#created?` methods, so you can act on updated/created items only. For instance:

```ruby
postprocess do
  @items.select(&:updated?).each do |item|
    $search_index.update(
      item.path,
      item.compiled_content(snapshot: :last),
    )
  end
end
```

**Comment by gjtorikian** [comment]
My specific use-case is in generating additional content that falls out of "normal" compilation. For example, given a Markdown file that looks like this:

``` markdown
title: A title
redirects_from:
  - /some-title/
  - /nowhere/
```

I want two new HTML files in *output/some-title/index.html* and *output/nowhere/* with some client-side set up, like:

```
<meta http-equiv=refresh content="0; url=/a-title/}">
<h1>Redirecting...</h1>
<a href="/a-title/">Click here if you are not redirected.</a>
<script>location='/a-title/'</script>
```

I started doing this in a preprocess, and was adding new `Nanoc::Int::Item`s to the mutable collection, but then the build started complaining and wanting to track those new items with compile and routing steps. My workaround for that started to feel hokey and I just wanted to be able to operate with the same data, but outside all the Rules.


> This could be extended by letting item instances (and item rep instances) within the postprocess block have #updated? and/or #created? methods, so you can act on updated/created items only.

I like that a lot.

**Comment by bobthecow** [comment]
You can route and compile the original item two times using a rep. It works rather well for things like this.

**Comment by gjtorikian** [comment]
Yeah, I actually solved my initial problem outside of the scope of needing a postprocessor. But given that it's a long-standing request I thought I might try my hand at it.

**Comment by bobthecow** [comment]
Fair enough. I wouldn't complain :)

**Comment by remko** [comment]
I would also like a postprocessing step. In my case, I want to do global optimization steps on the website: compressing assets, cachebusting assets and rewriting the URLs pointing to it, ... In general, things that are independent of the actual content (i.e. don't create new files), that you don't want/need to do while working on the content of the website (i.e. don't need to be part of 'compile'), and are either slow or awkward (or not possible) to do by squeezing it into the content processing (because it's orthogonal and/or they require a 'global' view on the site).

 I'm currently solving it with a rake task that rsyncs the output dir to a new dir, and do all the postprocessing on that dir, before deploying it. This unfortunately means i need to pull the deploying out of nanoc too and create a rake task for it.
