### ISSUE TITLE
Can't passthrough dotfiles?

### ISSUE THREAD

**Issue by gjtorikian** [nanoc/nanoc#754]
I just noticed that files starting with a dot—like `. nojekyll`—are not handled by Nanoc at all. They don't appear in the output, and they don't generate an error if they are missing in Rules.

**Comment by ddfreyne** [comment]
This is intentional, because hidden files can cause a world of pain (they’re invisible! why is my site not compiling!!!) and so the recommended approach to deal with hidden files is not have them hidden in the `content/` directory (e.g. `content/nojekyll`) and routed to a hidden location (e.g. `output/.nojekyll`).

The implementation of the `#all_files_and_dirs_in ` method uses `Dir.glob` which, won’t return hidden files when given the `*` glob ([code](https://github.com/nanoc/nanoc/blob/61104939f7b0ecf47563d6b1a69c02659b24ea2b/lib/nanoc/extra/filesystem_tools.rb#L108)).

If nothing else, I believe the Nanoc documentation should clarify that hidden files will be ignored, and that the non-hidden-to-hidden technique described above is the recommended approach.

Changing Nanoc to include hidden files will almost certainly break sites.

Alternative, a configuration option to (not) ignore hidden files might be worth it. (But with non-ignored hidden files, people will need to deal with e.g. `.DS_Store` manually.)

Opinions?

**Comment by gjtorikian** [comment]
Just as there's an option for `prune` to not purge certain paths, it might be nice to have an explicit "include these files" option. This would allow me to define *.nojekyll* but ignore every other dotfile.

Your explanation reminds me that Jekyll has [a similar configuration option called `include`](http://jekyllrb.com/docs/configuration/) for this same reason.

**Comment by ddfreyne** [comment]
I’ve decided to document the current behavior (which I think makes sense) rather than add configuration or custom behavior to deal with dotfiles. There’s now a [hidden files troubleshooting section](http://nanoc.ws/doc/troubleshooting/#hidden-files-are-ignored) on the Nanoc we bsite.

**Comment by ddfreyne** [comment]
Gah! I remembered only today that [Nanoc 3.7.5](http://nanoc.ws/release-notes/#3-7-5-2015-01-12) introduced an `extra_files` config option, which you can use to pass through dotfiles (e.g. `e.g. extra_files: ['.nojekyll']`).

I’ve created nanoc/nanoc.ws#176 to track this.

**Comment by gjtorikian** [comment]
Hah! Thank you. 😁
