### ISSUE TITLE
@item.compiled_content crashes

### ISSUE THREAD

**Issue by Ecco** [nanoc/nanoc#836]
The [documentation](http://nanoc.ws/doc/reference/variables/) says

> The @item variable contains the item that is currently being processed. This variable is available within compilation and routing rules, as well as while filtering and laying out an item.

Then a few lines after, 

> @item.compiled_content → String

But trying to use that method in a routing or compilation rule raises an exception :

```
NoMethodError: undefined method `compiled_content' for #<Nanoc::ItemWithoutRepsView:0x007faefaaa9870>
```

**Comment by Ecco** [comment]
Please don't fix it by removing the feature, it's definitely useful.

**Comment by ddfreyne** [comment]
It’s not possible to access the compiled content in a routing or compilation rule, because the content hasn’t been compiled yet at that point. Can you give an example of why this is useful for you?

You can access the raw content of an item using `@item.raw_content` though.

**Comment by Ecco** [comment]
My understanding is that the compilation process first builds an item dependency graph. This graph shouldn't have any cycle otherwise the compilation process cannot happen. Once this acyclic graph has been built, the compiler walks the graph and builds items in the "right" order (to ensure items depending on others are built after them)

That being said, the build of a given item is a two-step process : first filter, then route. On a **given** item, routing should happen after filtering, and filtering shouldn't depend on routing. Those are two sequential operations.

The use case is pretty simple : content-based cache busting. You route an item based on its compiled content, and add a hash at the end of the routed item (just like sprockets does, for example). This allows for far-future caching headers, which are very useful.

**Comment by ddfreyne** [comment]
The routing rules are executed _before_ the compilation rules, because they are necessary in order to determine which items need to be recompiled. It the output file already exists and the input is not outdated, the item does not need to be compiled. (This is essentially a chicken-and-egg problem.)

Because of this reason, accessing the compiled content from within a routing rule does not work. In Nanoc 3.x, this was possible but would return unreliable results. In Nanoc 4.x, it’s outright impossible, because the `#compiled_content` method is not available in routing and compilation rules.

Content-based cache busting using routing rules is not possible in Nanoc. There’s a few alternatives (from bad to good):

1. Hardcode a version number
2. Let a checksum be based off the raw contents of the filename (without dependencies)
3. Generate a checksum based on the raw contents of this file + dependent files (lots of work!)
4. Generate a checksum from the _compiled_ content and use it in a query string

I haven’t tried the last approach, but it seems promising. You’d end up with a helper like the following:

```ruby
def stylesheet_path
  stylesheet = @items['/assets/stylesheet.*']
  stylesheet.path + '?v' + Digest::SHA256.hexdigest(stylesheet.compiled_content)
end
```

**Comment by Ecco** [comment]
Thanks for taking some time to write this comprehensive reply. Unfortunately solution number 4 has proven unreliable in the past. See [Rails' asset pipeline doc](http://edgeguides.rubyonrails.org/asset_pipeline.html#what-is-fingerprinting-and-why-should-i-care-questionmark) for an explanation why.

I do like solution number 3 though. It's actually even more efficient, since we don't need the content to be compiled before hashing.

**Comment by ddfreyne** [comment]
> Unfortunately solution number 4 has proven unreliable in the past.

Yes; that’s what I figured. (Though I’m not sure whether it’s still as big of a problem as it used to be.)

> I do like solution number 3 though.

If there’s only a handful of files, that can work with not much effort. I hope to be able to expose the dependency graph in some future version of Nanoc, so that this could be done more easily, but for the time being, it can only be done manually.

> It's actually even more efficient, since we don't need the content to be filtered to tell wether it's been modified.

Nanoc caches compiled content, so for unchanged items, this wouldn’t be much of a slowdown.

**Comment by ddfreyne** [comment]
I’ll close this issue now, but I’m happy to keep the discussion going.

**Comment by Ecco** [comment]
Great ! I'll see if I can come up with something.

Note that regarding that specific issue, the doc is still wrong though :-)

**Comment by ddfreyne** [comment]
`#compiled_content` *is* still available, although not during preprocessing or within rules. I admit that it’s a little unclear, but I’ve opened nanoc/nanoc.ws#158 so I remember to fix it.

**Comment by Ecco** [comment]
Thanks! Denis, would you mind telling me the main steps that what would need to be done to implement solution number three ?

**Comment by ddfreyne** [comment]
@Ecco Something along the lines of this (untested):

```ruby
Digest::SHA1.hexdigest(
  @items.find_all('/assets/**/*.css').map(&:raw_content).join(''))
```

**Comment by rosetree** [comment]
I implemented this feature in my blog by first excluding the SASS compilation from the `nanoc build` (https://github.com/rosetree/plasisent.org/commit/14772ccf30ccb394c64b5b836847054b37807363) and later used the SHA1 hash as filename (https://github.com/rosetree/plasisent.org/commit/61795e09b262e1390be94657222d8c1761f35ecb). It’s a bit like the second solution, @ddfreyne suggested, but my approach makes sure, that the CSS file doesn’t have any dependencies on compile time.
