### ISSUE TITLE
Compilation fails when creating a folder when file exists in output folder

### ISSUE THREAD

**Issue by myncke** [nanoc/nanoc#942]
### Summary

File does not get deleted in output folder prior to creating new folder.

### Steps to reproduce

1. make file without extension
2. make a route to create a folder with the file name of step 1

### Expected behavior

Delete the file, create the folder.

### Actual behavior

Crashes

### Crash log

https://gist.github.com/myncke/e2aeed489eda1d3131e08385724919df

**Comment by ddfreyne** [comment]
This situation is tricky to solve in a general way, because there’s situations in which the expected behavior is not so clear. For example:

1. Route one item to `/foo`
2. Route another item to `/foo/bar`

In this case, the proper solution is to error out. (With whatever is the most appropriate error—which might or might not be `Errno::EEXIST`.)

For this bug in particular, though, it seems that changing the order of pruning and compiling so that pruning is done _first_, rather than last, would solve the problem. The caveat here is that if pruning is not enabled, this error will still occur… which I believe is fine.

**Comment by ddfreyne** [comment]
Fix in #946.
