### ISSUE TITLE
It should be more obvious that helpers need to be explicitly included

### ISSUE THREAD

**Issue by connorshea** [nanoc/nanoc#952]
Just struggled with this for about 15 minutes (maybe I'm just dumb) so I figured I'd open an issue.

It's not clear that the default helpers aren't included by default. I kept getting errors about `link_to` not being defined and assumed I hadn't used it properly. It started working once I added a `lib/helpers.rb` file that included the `LinkTo` helper, but that's not nearly clear enough from the documentation.

There should be something at the top of [this page](http://nanoc.ws/doc/reference/helpers/) explaining how helpers need to be explicitly included. Currently the only page that has this notice is the [other Helpers page](http://nanoc.ws/doc/helpers/).

Some other ideas:

- Merge the two Helpers pages, two Filters pages, etc. It's weird to me that they're separate.
- Just include the default helpers by default, or at least generate the site with a `lib/helpers.rb` file already defined.

**Comment by ddfreyne** [comment]
Good point! I believe I’ll go with describing how to activate helpers on the helpers reference page.

The reference is separate from the guide because the former is a rather long list that’s mainly useful as reference material (which I don’t think you’d necessarily read through unless you’re looking for something specific), while the latter is more conceptual documentation on helpers in general.

Including the helpers by default would cause conflicts. I don’t like the idea of pre-populating `lib/helpers.rb` as the helpers are fairly opinionated and I quite like the idea of having a bare-bones site.

I suggest:

* Adding a short description on how to enable helpers on the helpers reference page, and link to the helpers guide.

* Adding a troubleshooting entry that deals with helpers not being available.

**Comment by ddfreyne** [comment]
As a start, I’ve added a note at the top of the helpers reference page:

![screen shot 2016-10-15 at 08 58 26](https://cloud.githubusercontent.com/assets/6269/19408109/a27210b4-92b5-11e6-9370-2e2477c05e2b.png)

**Comment by ddfreyne** [comment]
I also added a troubleshooting entry. I’ll mark this issue as complete now!

**Comment by connorshea** [comment]
Thanks!

**Comment by connorshea** [comment]
@ddfreyne I didn't want to open an issue for this, so I figured I'd just comment here.

We just launched a new Docs site for GitLab, built with Nanoc, at https://docs.gitlab.com/

Source here: https://gitlab.com/gitlab-com/gitlab-docs

Just wanted to say thanks for the project, this is so much better than the bash script we previously had! 🙈
